# Generated by Django 5.2.2 on 2025-07-14 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='Id_cliente', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('cedula', models.IntegerField()),
                ('ntelefonico', models.IntegerField(blank=True, db_column='Ntelefonico', null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(db_column='Id_empleado', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('cedula', models.IntegerField(unique=True)),
                ('edad', models.IntegerField()),
                ('profesion', models.TextField()),
                ('ntelefonico', models.IntegerField(blank=True, db_column='Ntelefonico', null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id_caso', models.AutoField(db_column='Id_caso', primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=20)),
                ('informacion', models.TextField()),
                ('n_de_caso', models.IntegerField(db_column='N_de_caso')),
                ('documentacion', models.TextField(blank=True, null=True)),
                ('pk_cliente', models.ForeignKey(blank=True, db_column='Pk_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente')),
                ('abogados', models.ManyToManyField(blank=True, to='app.empleado')),
            ],
            options={
                'db_table': 'caso',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(db_column='Id_pago', primary_key=True, serialize=False)),
                ('pago', models.IntegerField()),
                ('pk_caso', models.ForeignKey(db_column='PK_caso', on_delete=django.db.models.deletion.DO_NOTHING, to='app.caso')),
                ('pk_cliente', models.ForeignKey(db_column='PK_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
    ]
