# Generated by Django 5.2.2 on 2025-07-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='documentacion_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
