# Generated by Django 5.2.4 on 2025-07-25 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_caso_documentacion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='abogado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empleado'),
        ),
    ]
